{
  pkgs,
  config,
  lib,
  ...
}:
let
  cfg = config.services.hydra-github-app;
in
{
  options.services.hydra-github-app = {
    enable = lib.mkEnableOption "hydra-github-app";
    package = lib.mkPackageOption pkgs "hydra-github-app" { default = null; } // {
      default = pkgs.callPackage ./package.nix { };
      defaultText = lib.literalExpression "pkgs.callPacakges ./package.nix";
    };
    settings = lib.mkOption {
      description = "Configuration options that will be passed to the daemon";
      default = { };
      type = lib.types.submodule {
        options = {
          listen = lib.mkOption {
            description = "IPv4 or IPv6 address and port that the webhook server will listen on (see Rust stdlib documentation for the supported textual representations for [IPv4](https://doc.rust-lang.org/std/net/struct.SocketAddrV4.html#textual-representation) and [IPv6](https://doc.rust-lang.org/std/net/struct.SocketAddrV6.html#textual-representation))";
            type = lib.types.nonEmptyStr;
            example = "127.0.0.1:3000";
          };
          user_agent = lib.mkOption {
            description = "a string that will be used as `User-Agent` header for HTTP requests. GitHub [requires](https://docs.github.com/en/rest/using-the-rest-api/troubleshooting-the-rest-api?apiVersion=2022-11-28#user-agent-required) it to be valid";
            type = lib.types.nonEmptyStr;
            example = "my-hydra-app";
          };
          github_app = {
            webhook_secret_file = lib.mkOption {
              description = "a path to the file containing GitHub webhook secret. It can be any text specified during webhook creation in GitHub";
              type = lib.types.externalPath;
            };
            app_private_key_file = lib.mkOption {
              description = "a path to the file containing GitHub app's private key generated in the GitHub app's settings";
              type = lib.types.externalPath;
            };
            app_id = lib.mkOption {
              description = "the ID of the GitHub app, can be obtained on the GitHub app's settings page";
              type = lib.types.ints.positive;
            };
            client_id = lib.mkOption {
              description = "the client ID of the GitHub app, can be obtained on the GitHub app's settings page";
              type = lib.types.nonEmptyStr;
            };
          };
          hydra = {
            url = lib.mkOption {
              description = "the base URL for Hydra instance where jobsets will be created";
              type = lib.types.nonEmptyStr;
            };
            user = lib.mkOption {
              description = "user name used to authenticate in Hydra";
              type = lib.types.nonEmptyStr;
            };
            # FIXME: pass password as file or smth
            password_env = lib.mkOption {
              description = "environment variable with password used to authenticate in Hydra";
              type = lib.types.nonEmptyStr;
            };
            project = lib.mkOption {
              description = "name of the project in Hydra where jobsets will be created and watched";
              type = lib.types.nonEmptyStr;
            };
          };
          repositories = lib.mkOption {
            description = "an object with full names (`\"ORG/REPO\"`) of the GitHub repositories that are allowed to trigger Hydra builds as keys";
            type = lib.types.attrsOf (
              lib.types.submodule {
                options = {
                  check_run_name = lib.mkOption {
                    description = "the name of the check representing the whole jobset that will be created on each commit";
                    type = lib.types.nonEmptyStr;
                  };
                  check_per_job = lib.mkOption {
                    description = "if enabled, every job in the jobset will be represented as a separate check named after its attribute path";
                    type = lib.types.bool;
                    default = false;
                  };
                  hydra_jobset_template = lib.mkOption {
                    description = ''
                      a representation of Hydra jobset configuration with following allowances:
                      * `description` field can contain `{pr_url}` string that will be replaced with the URL of the PR that triggered this jobset;
                      * `inputs` for legacy jobsets can contain inputs with no values with special types:
                          * `pr head` will be replaced with `git` input pointing to the tip of the PR's branch;
                          * `pr base` will be replaced with `git` input pointing to the tip of the PR's target branch;
                          * `pr merge` will be replaced with `git` input pointing to the PR merge commit generated by GitHub;
                      * special string inputs will be added:
                          * `repository_name` containing the name of the repository from which the jobset was triggered;
                          * `pr_number` containing the number of the PR that triggered the jobset.
                      * `flake` field if present can match `{pr head}`, `{pr base}` or `{pr merge}` to be replaced with the appropriate flake URI (see above)
                    '';
                    type = lib.types.json;
                  };
                };
              }
            );
          };
        };
      };
    };
  };
  config = lib.mkIf cfg.enable {
    systemd.services.hydra-github-app = {
      description = "Hydra GitHub app";
      wantedBy = [ "multi-user.target" ];
      after = [ "network.target" ];
      serviceConfig = {
        Type = "simple";
        DynamicUser = true;
        ExecStart = ''
          ${pkgs.lib.getExe cfg.package} ${pkgs.writers.writeJSON "config.json" cfg.settings} webhook
        '';
        Restart = "on-failure";
        RestartSec = "5s";
        StandardOutput = "journal";
        StandardError = "journal";
      };
    };
  };
}
